# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'E-commerce' do
pod 'ImageSlideshow', '~> 1.9.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for E-commerce

end
